C     ----------------------------------------------------------------
C     Double-precision port of src/original/jtutil.f
C     original SHA-256: c8a3a2b2090e7e92085e4db742176b1a292078d2f5fea10daae41aeb1185d570
C     This is a maintained precision port, not the historical original
C     (which is kept unchanged in src/original/ and stays the reference).
C     Generated by tools/precision_port.py; do not edit by hand.
C     Permitted changes: precision declarations (REAL -> DOUBLE
C     PRECISION, IMPLICIT DOUBLE PRECISION), real literals written with
C     a D exponent (same decimal value), precision-specific intrinsics
C     (ALOG, ALOG10, AMIN1, AMAX1, FLOAT, SNGL -> generic forms),
C     renamed routines and COMMON blocks, and explicitly reviewed
C     numerical-range protections marked "PRECISION PORT".
C     ----------------------------------------------------------------
      DOUBLE PRECISION FUNCTION amediand(n,x)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      double precision x(2)
      if(n.eq.0) then
         amediand = 0
         return
      else if(n.eq.1) then
         amediand = x(1)
         return
      end if
      do 913 k = 2,n
         amediand = x(k)
         do 914 l = k-1,1,-1
            if(x(l).le.amediand) goto 915
            x(l+1) = x(l)
 914     continue
         l = 0
 915     x(l+1) = amediand
 913  continue
      amediand = 0.5D0*(x((n+1)/2)+x((n+2)/2))
      return
      end

      SUBROUTINE fitwlpolyd(NPT,X,Y,W,SCALE,NCOEFF,COEFF)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
* X and Y are data arrays with NPT points to fit.
* W is a weight array, so that Sum W * (Y-Yfit)**2 is minimized
* SCALE returns A and B,
* where Z = A * (X - B) is the variable given to the polynomials.
* A polynomial of degree NCOEFF-1 is fit and the coefficients are
* returned in COEFF.
      double precision X(NPT), Y(NPT), SCALE(2), W(NPT)
      double precision coeff(ncoeff)
      call dofitlpolyd(NPT,X,Y,W,SCALE,NCOEFF,COEFF,1)
      return
      end

      SUBROUTINE dofitlpolyd(NPT,X,Y,W,SCALE,NCOEFF,COEFF,iwgt)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
* X and Y are data arrays with NPT points to fit.
* W is a weight array, so that Sum W * (Y-Yfit)**2 is minimized
* SCALE returns A and B,
* where Z = A * (X - B) is the variable given to the polynomials.
* A polynomial of degree NCOEFF-1 is fit and the coefficients are
* returned in COEFF.
      PARAMETER (MAXFIT=8)
      double precision COV(MAXFIT*MAXFIT), VEC(MAXFIT)
      double precision COEFF(NCOEFF)
      double precision A, B, Z, LPI, DET
      double precision X(NPT), Y(NPT), SCALE(2), W(NPT)
      
      scale(1) = x(1)
      scale(2) = x(1)
      do 2 i = 2,npt
         scale(1) = min(scale(1),x(i))
         scale(2) = max(scale(2),x(i))
 2    continue

      A = 2.0D0 / (SCALE(2) - SCALE(1))
      B = 0.5D0 * (SCALE(2) + SCALE(1))
      
      DO 5 J = 1,NCOEFF
         VEC(J) = 0
 5    CONTINUE
      DO 6 I = 1,NCOEFF*NCOEFF
         COV(I) = 0
 6    CONTINUE
      DO 10 N = 1,NPT
         Z = A * (DBLE(X(N)) - B)
         
         DO 21 J = 1,NCOEFF
            COEFF(J) = LPI(J,Z)
            if(iwgt.eq.0) then
               VEC(J) = VEC(J) + COEFF(J) * Y(N)
            else
               VEC(J) = VEC(J) + COEFF(J) * Y(N) * W(N)
            end if
            DO 20 I = 1,J
               if(iwgt.eq.0) then
                  COV((J-1)*NCOEFF+I) = COV((J-1)*NCOEFF+I) + 
     $                 COEFF(I) * COEFF(J)
               else
                  COV((J-1)*NCOEFF+I) = COV((J-1)*NCOEFF+I) + 
     $                 COEFF(I) * COEFF(J) * W(N)
               end if
 20         CONTINUE
 21      CONTINUE
 10   CONTINUE
      
      DO 31 J = 2,NCOEFF
         DO 30 I = 1,J-1
            COV((I-1)*NCOEFF+J) = COV((J-1)*NCOEFF+I)
 30      CONTINUE
 31   CONTINUE
      CALL INVERT(NCOEFF,COV,DET)
      IF(DET.EQ.0) THEN
         WRITE(6,*) 'FITWLPOLY: singular covariance matrix'
         RETURN
      END IF
      
      DO 41 J = 1,NCOEFF
         COEFF(J) = 0
         DO 40 I = 1,NCOEFF
            COEFF(J) = COEFF(J) + COV((J-1)*NCOEFF+I) * VEC(I)
 40      CONTINUE
 41   CONTINUE
      SCALE(1) = dble(A)
      SCALE(2) = dble(B)
      
      RETURN
      END
      
      double precision FUNCTION lpolyd(X,SCALE,NCOEFF,COEFF)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      double precision COEFF(1)
      double precision TEMP, Z, LPI
      double precision SCALE(2)
      Z = SCALE(1) * (X - SCALE(2))
      TEMP = 0
      DO 10 I = 1,NCOEFF
         TEMP = TEMP + COEFF(I) * LPI(I,Z)
 10   CONTINUE
      lpolyd = dble(TEMP)
      RETURN
      END

      DOUBLE PRECISION FUNCTION bcd(n,k)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
* Binomial coefficient of (n k), divided by 2^n
      inum = 1
      idenom = 1
      do 10 i = k+1,n
         inum = inum * i
         idenom = idenom * (i-k)
 10   continue
      ibc = inum / idenom
      bcd = dble(ibc)/2**n
      return
      end

      DOUBLE PRECISION FUNCTION zbrentd(FUNC,X1,X2,fx1,fx2,TOL)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      PARAMETER (ITMAX=100,EPS=3.D-8)
      EXTERNAL FUNC
      zbrentd = 0
      A=X1
      B=X2
C      FA=FUNC(A)
C      FB=FUNC(B)
      FA=Fx1
      FB=Fx2
      IF(FB*FA.GT.0.D0) THEN
         write(6,*) 'Root must be bracketed for ZBRENT.'
         return
      END IF
      FC=FB
      DO 11 ITER=1,ITMAX
        IF(FB*FC.GT.0.D0) THEN
          C=A
          FC=FA
          D=B-A
          E=D
        ENDIF
        IF(ABS(FC).LT.ABS(FB)) THEN
          A=B
          B=C
          C=A
          FA=FB
          FB=FC
          FC=FA
        ENDIF
        TOL1=2.D0*EPS*ABS(B)+0.5D0*TOL
        XM=.5D0*(C-B)
        IF(ABS(XM).LE.TOL1 .OR. FB.EQ.0.D0)THEN
          zbrentd=B
          RETURN
        ENDIF
        IF(ABS(E).GE.TOL1 .AND. ABS(FA).GT.ABS(FB)) THEN
          S=FB/FA
          IF(A.EQ.C) THEN
            P=2.D0*XM*S
            Q=1.D0-S
          ELSE
            Q=FA/FC
            R=FB/FC
            P=S*(2.D0*XM*Q*(Q-R)-(B-A)*(R-1.D0))
            Q=(Q-1.D0)*(R-1.D0)*(S-1.D0)
          ENDIF
          IF(P.GT.0.D0) Q=-Q
          P=ABS(P)
          IF(2.D0*P .LT. MIN(3.D0*XM*Q-ABS(TOL1*Q),ABS(E*Q))) THEN
            E=D
            D=P/Q
          ELSE
            D=XM
            E=D
          ENDIF
        ELSE
          D=XM
          E=D
        ENDIF
        A=B
        FA=FB
        IF(ABS(D) .GT. TOL1) THEN
          B=B+D
        ELSE
          B=B+SIGN(TOL1,XM)
        ENDIF
        FB=FUNC(B)
11    CONTINUE
      write(6,*) 'ZBRENT exceeding maximum iterations.'
      zbrentd=B
      RETURN
      END


